### ISSUE TITLE
Code won't compile

### ISSUE THREAD

**Issue by xavierpantet** [PerfectlySoft/Perfect-MongoDB#24]
Hello,
I just updated to Swift5 and I am not able to compile my project anymore. Indeed, I have a lot of type errors especially due to pointers. For example:
```
error: cannot convert value of type 'UnsafeMutablePointer<bson_t>' (aka 'UnsafeMutablePointer<_bson_t>') to expected argument type 'OpaquePointer?'
```
or
```
error: '&' used with non-inout argument of type 'OpaquePointer?'
```
Do you have any suggestion?
Thank you!

**Comment by kjessup** [comment]
A fix/update is in progress. I'll report back here when it's complete.

**Comment by kjessup** [comment]
I just committed and tagged version 3.1.2. It should be good with Swift 4.1, 4.2, and 5.

**Comment by xavierpantet** [comment]
Yep, it works! Thank you!
